/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
} from '@solana/kit';

export type RepaidRentFundDebt = {
  user: Address;
  amount: bigint;
  remainingUserClaim: bigint;
};

export type RepaidRentFundDebtArgs = {
  user: Address;
  amount: number | bigint;
  remainingUserClaim: number | bigint;
};

export function getRepaidRentFundDebtEncoder(): Encoder<RepaidRentFundDebtArgs> {
  return getStructEncoder([
    ['user', getAddressEncoder()],
    ['amount', getU64Encoder()],
    ['remainingUserClaim', getU64Encoder()],
  ]);
}

export function getRepaidRentFundDebtDecoder(): Decoder<RepaidRentFundDebt> {
  return getStructDecoder([
    ['user', getAddressDecoder()],
    ['amount', getU64Decoder()],
    ['remainingUserClaim', getU64Decoder()],
  ]);
}

export function getRepaidRentFundDebtCodec(): Codec<
  RepaidRentFundDebtArgs,
  RepaidRentFundDebt
> {
  return combineCodec(
    getRepaidRentFundDebtEncoder(),
    getRepaidRentFundDebtDecoder()
  );
}
