/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  isProgramError,
  type Address,
  type SOLANA_ERROR__INSTRUCTION_ERROR__CUSTOM,
  type SolanaError,
} from '@solana/kit';
import { SVM_SPOKE_PROGRAM_ADDRESS } from '../programs';

/** InvalidQuoteTimestamp: Invalid quote timestamp! */
export const SVM_SPOKE_ERROR__INVALID_QUOTE_TIMESTAMP = 0x1770; // 6000
/** InvalidFillDeadline: Invalid fill deadline! */
export const SVM_SPOKE_ERROR__INVALID_FILL_DEADLINE = 0x1771; // 6001
/** NotExclusiveRelayer: Caller is not the exclusive relayer and exclusivity deadline has not passed! */
export const SVM_SPOKE_ERROR__NOT_EXCLUSIVE_RELAYER = 0x1772; // 6002
/** NoSlowFillsInExclusivityWindow: The Deposit is still within the exclusivity window! */
export const SVM_SPOKE_ERROR__NO_SLOW_FILLS_IN_EXCLUSIVITY_WINDOW = 0x1773; // 6003
/** RelayFilled: The relay has already been filled! */
export const SVM_SPOKE_ERROR__RELAY_FILLED = 0x1774; // 6004
/** InvalidSlowFillRequest: Slow fill requires status of Unfilled! */
export const SVM_SPOKE_ERROR__INVALID_SLOW_FILL_REQUEST = 0x1775; // 6005
/** ExpiredFillDeadline: The fill deadline has passed! */
export const SVM_SPOKE_ERROR__EXPIRED_FILL_DEADLINE = 0x1776; // 6006
/** InvalidMerkleProof: Invalid Merkle proof! */
export const SVM_SPOKE_ERROR__INVALID_MERKLE_PROOF = 0x1777; // 6007
/** InvalidChainId: Invalid chain id! */
export const SVM_SPOKE_ERROR__INVALID_CHAIN_ID = 0x1778; // 6008
/** InvalidMerkleLeaf: Invalid Merkle leaf! */
export const SVM_SPOKE_ERROR__INVALID_MERKLE_LEAF = 0x1779; // 6009
/** ClaimedMerkleLeaf: Leaf already claimed! */
export const SVM_SPOKE_ERROR__CLAIMED_MERKLE_LEAF = 0x177a; // 6010
/** DepositsArePaused: Deposits are currently paused! */
export const SVM_SPOKE_ERROR__DEPOSITS_ARE_PAUSED = 0x177b; // 6011
/** FillsArePaused: Fills are currently paused! */
export const SVM_SPOKE_ERROR__FILLS_ARE_PAUSED = 0x177c; // 6012
/** InsufficientSpokePoolBalanceToExecuteLeaf: Insufficient spoke pool balance to execute leaf */
export const SVM_SPOKE_ERROR__INSUFFICIENT_SPOKE_POOL_BALANCE_TO_EXECUTE_LEAF = 0x177d; // 6013
/** InvalidExclusiveRelayer: Invalid exclusive relayer! */
export const SVM_SPOKE_ERROR__INVALID_EXCLUSIVE_RELAYER = 0x177e; // 6014
/** InvalidOutputToken: Invalid output token! */
export const SVM_SPOKE_ERROR__INVALID_OUTPUT_TOKEN = 0x177f; // 6015

export type SvmSpokeError =
  | typeof SVM_SPOKE_ERROR__CLAIMED_MERKLE_LEAF
  | typeof SVM_SPOKE_ERROR__DEPOSITS_ARE_PAUSED
  | typeof SVM_SPOKE_ERROR__EXPIRED_FILL_DEADLINE
  | typeof SVM_SPOKE_ERROR__FILLS_ARE_PAUSED
  | typeof SVM_SPOKE_ERROR__INSUFFICIENT_SPOKE_POOL_BALANCE_TO_EXECUTE_LEAF
  | typeof SVM_SPOKE_ERROR__INVALID_CHAIN_ID
  | typeof SVM_SPOKE_ERROR__INVALID_EXCLUSIVE_RELAYER
  | typeof SVM_SPOKE_ERROR__INVALID_FILL_DEADLINE
  | typeof SVM_SPOKE_ERROR__INVALID_MERKLE_LEAF
  | typeof SVM_SPOKE_ERROR__INVALID_MERKLE_PROOF
  | typeof SVM_SPOKE_ERROR__INVALID_OUTPUT_TOKEN
  | typeof SVM_SPOKE_ERROR__INVALID_QUOTE_TIMESTAMP
  | typeof SVM_SPOKE_ERROR__INVALID_SLOW_FILL_REQUEST
  | typeof SVM_SPOKE_ERROR__NO_SLOW_FILLS_IN_EXCLUSIVITY_WINDOW
  | typeof SVM_SPOKE_ERROR__NOT_EXCLUSIVE_RELAYER
  | typeof SVM_SPOKE_ERROR__RELAY_FILLED;

let svmSpokeErrorMessages: Record<SvmSpokeError, string> | undefined;
if (process.env.NODE_ENV !== 'production') {
  svmSpokeErrorMessages = {
    [SVM_SPOKE_ERROR__CLAIMED_MERKLE_LEAF]: `Leaf already claimed!`,
    [SVM_SPOKE_ERROR__DEPOSITS_ARE_PAUSED]: `Deposits are currently paused!`,
    [SVM_SPOKE_ERROR__EXPIRED_FILL_DEADLINE]: `The fill deadline has passed!`,
    [SVM_SPOKE_ERROR__FILLS_ARE_PAUSED]: `Fills are currently paused!`,
    [SVM_SPOKE_ERROR__INSUFFICIENT_SPOKE_POOL_BALANCE_TO_EXECUTE_LEAF]: `Insufficient spoke pool balance to execute leaf`,
    [SVM_SPOKE_ERROR__INVALID_CHAIN_ID]: `Invalid chain id!`,
    [SVM_SPOKE_ERROR__INVALID_EXCLUSIVE_RELAYER]: `Invalid exclusive relayer!`,
    [SVM_SPOKE_ERROR__INVALID_FILL_DEADLINE]: `Invalid fill deadline!`,
    [SVM_SPOKE_ERROR__INVALID_MERKLE_LEAF]: `Invalid Merkle leaf!`,
    [SVM_SPOKE_ERROR__INVALID_MERKLE_PROOF]: `Invalid Merkle proof!`,
    [SVM_SPOKE_ERROR__INVALID_OUTPUT_TOKEN]: `Invalid output token!`,
    [SVM_SPOKE_ERROR__INVALID_QUOTE_TIMESTAMP]: `Invalid quote timestamp!`,
    [SVM_SPOKE_ERROR__INVALID_SLOW_FILL_REQUEST]: `Slow fill requires status of Unfilled!`,
    [SVM_SPOKE_ERROR__NO_SLOW_FILLS_IN_EXCLUSIVITY_WINDOW]: `The Deposit is still within the exclusivity window!`,
    [SVM_SPOKE_ERROR__NOT_EXCLUSIVE_RELAYER]: `Caller is not the exclusive relayer and exclusivity deadline has not passed!`,
    [SVM_SPOKE_ERROR__RELAY_FILLED]: `The relay has already been filled!`,
  };
}

export function getSvmSpokeErrorMessage(code: SvmSpokeError): string {
  if (process.env.NODE_ENV !== 'production') {
    return (svmSpokeErrorMessages as Record<SvmSpokeError, string>)[code];
  }

  return 'Error message not available in production bundles.';
}

export function isSvmSpokeError<TProgramErrorCode extends SvmSpokeError>(
  error: unknown,
  transactionMessage: {
    instructions: Record<number, { programAddress: Address }>;
  },
  code?: TProgramErrorCode
): error is SolanaError<typeof SOLANA_ERROR__INSTRUCTION_ERROR__CUSTOM> &
  Readonly<{ context: Readonly<{ code: TProgramErrorCode }> }> {
  return isProgramError<TProgramErrorCode>(
    error,
    transactionMessage,
    SVM_SPOKE_PROGRAM_ADDRESS,
    code
  );
}
