/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getStructDecoder,
  getStructEncoder,
  type Codec,
  type Decoder,
  type Encoder,
} from '@solana/kit';

export type Pause = {};

export type PauseArgs = Pause;

export function getPauseEncoder(): Encoder<PauseArgs> {
  return getStructEncoder([]);
}

export function getPauseDecoder(): Decoder<Pause> {
  return getStructDecoder([]);
}

export function getPauseCodec(): Codec<PauseArgs, Pause> {
  return combineCodec(getPauseEncoder(), getPauseDecoder());
}
