/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getStructDecoder,
  getStructEncoder,
  getU32Decoder,
  getU32Encoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
} from '@solana/kit';

export type TokenPairUnlinked = {
  localToken: Address;
  remoteDomain: number;
  remoteToken: Address;
};

export type TokenPairUnlinkedArgs = TokenPairUnlinked;

export function getTokenPairUnlinkedEncoder(): Encoder<TokenPairUnlinkedArgs> {
  return getStructEncoder([
    ['localToken', getAddressEncoder()],
    ['remoteDomain', getU32Encoder()],
    ['remoteToken', getAddressEncoder()],
  ]);
}

export function getTokenPairUnlinkedDecoder(): Decoder<TokenPairUnlinked> {
  return getStructDecoder([
    ['localToken', getAddressDecoder()],
    ['remoteDomain', getU32Decoder()],
    ['remoteToken', getAddressDecoder()],
  ]);
}

export function getTokenPairUnlinkedCodec(): Codec<
  TokenPairUnlinkedArgs,
  TokenPairUnlinked
> {
  return combineCodec(
    getTokenPairUnlinkedEncoder(),
    getTokenPairUnlinkedDecoder()
  );
}
