/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  getU32Decoder,
  getU32Encoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from '@solana/kit';
import { SVM_SPOKE_PROGRAM_ADDRESS } from '../programs';
import {
  expectAddress,
  getAccountMetaFactory,
  type ResolvedAccount,
} from '../shared';

export const INITIALIZE_INSTRUCTION_PARAMS_DISCRIMINATOR = new Uint8Array([
  94, 206, 190, 192, 127, 8, 186, 28,
]);

export function getInitializeInstructionParamsDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    INITIALIZE_INSTRUCTION_PARAMS_DISCRIMINATOR
  );
}

export type InitializeInstructionParamsInstruction<
  TProgram extends string = typeof SVM_SPOKE_PROGRAM_ADDRESS,
  TAccountSigner extends string | AccountMeta<string> = string,
  TAccountInstructionParams extends string | AccountMeta<string> = string,
  TAccountSystemProgram extends string | AccountMeta<string> =
    '11111111111111111111111111111111',
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountSigner extends string
        ? WritableSignerAccount<TAccountSigner> &
            AccountSignerMeta<TAccountSigner>
        : TAccountSigner,
      TAccountInstructionParams extends string
        ? WritableAccount<TAccountInstructionParams>
        : TAccountInstructionParams,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      ...TRemainingAccounts,
    ]
  >;

export type InitializeInstructionParamsInstructionData = {
  discriminator: ReadonlyUint8Array;
  totalSize: number;
};

export type InitializeInstructionParamsInstructionDataArgs = {
  totalSize: number;
};

export function getInitializeInstructionParamsInstructionDataEncoder(): Encoder<InitializeInstructionParamsInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ['discriminator', fixEncoderSize(getBytesEncoder(), 8)],
      ['totalSize', getU32Encoder()],
    ]),
    (value) => ({
      ...value,
      discriminator: INITIALIZE_INSTRUCTION_PARAMS_DISCRIMINATOR,
    })
  );
}

export function getInitializeInstructionParamsInstructionDataDecoder(): Decoder<InitializeInstructionParamsInstructionData> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
    ['totalSize', getU32Decoder()],
  ]);
}

export function getInitializeInstructionParamsInstructionDataCodec(): Codec<
  InitializeInstructionParamsInstructionDataArgs,
  InitializeInstructionParamsInstructionData
> {
  return combineCodec(
    getInitializeInstructionParamsInstructionDataEncoder(),
    getInitializeInstructionParamsInstructionDataDecoder()
  );
}

export type InitializeInstructionParamsAsyncInput<
  TAccountSigner extends string = string,
  TAccountInstructionParams extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  signer: TransactionSigner<TAccountSigner>;
  instructionParams?: Address<TAccountInstructionParams>;
  systemProgram?: Address<TAccountSystemProgram>;
  totalSize: InitializeInstructionParamsInstructionDataArgs['totalSize'];
};

export async function getInitializeInstructionParamsInstructionAsync<
  TAccountSigner extends string,
  TAccountInstructionParams extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof SVM_SPOKE_PROGRAM_ADDRESS,
>(
  input: InitializeInstructionParamsAsyncInput<
    TAccountSigner,
    TAccountInstructionParams,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress }
): Promise<
  InitializeInstructionParamsInstruction<
    TProgramAddress,
    TAccountSigner,
    TAccountInstructionParams,
    TAccountSystemProgram
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? SVM_SPOKE_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    signer: { value: input.signer ?? null, isWritable: true },
    instructionParams: {
      value: input.instructionParams ?? null,
      isWritable: true,
    },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.instructionParams.value) {
    accounts.instructionParams.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([
            105, 110, 115, 116, 114, 117, 99, 116, 105, 111, 110, 95, 112, 97,
            114, 97, 109, 115,
          ])
        ),
        getAddressEncoder().encode(expectAddress(accounts.signer.value)),
      ],
    });
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      '11111111111111111111111111111111' as Address<'11111111111111111111111111111111'>;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.signer),
      getAccountMeta(accounts.instructionParams),
      getAccountMeta(accounts.systemProgram),
    ],
    programAddress,
    data: getInitializeInstructionParamsInstructionDataEncoder().encode(
      args as InitializeInstructionParamsInstructionDataArgs
    ),
  } as InitializeInstructionParamsInstruction<
    TProgramAddress,
    TAccountSigner,
    TAccountInstructionParams,
    TAccountSystemProgram
  >;

  return instruction;
}

export type InitializeInstructionParamsInput<
  TAccountSigner extends string = string,
  TAccountInstructionParams extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  signer: TransactionSigner<TAccountSigner>;
  instructionParams: Address<TAccountInstructionParams>;
  systemProgram?: Address<TAccountSystemProgram>;
  totalSize: InitializeInstructionParamsInstructionDataArgs['totalSize'];
};

export function getInitializeInstructionParamsInstruction<
  TAccountSigner extends string,
  TAccountInstructionParams extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof SVM_SPOKE_PROGRAM_ADDRESS,
>(
  input: InitializeInstructionParamsInput<
    TAccountSigner,
    TAccountInstructionParams,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress }
): InitializeInstructionParamsInstruction<
  TProgramAddress,
  TAccountSigner,
  TAccountInstructionParams,
  TAccountSystemProgram
> {
  // Program address.
  const programAddress = config?.programAddress ?? SVM_SPOKE_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    signer: { value: input.signer ?? null, isWritable: true },
    instructionParams: {
      value: input.instructionParams ?? null,
      isWritable: true,
    },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      '11111111111111111111111111111111' as Address<'11111111111111111111111111111111'>;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.signer),
      getAccountMeta(accounts.instructionParams),
      getAccountMeta(accounts.systemProgram),
    ],
    programAddress,
    data: getInitializeInstructionParamsInstructionDataEncoder().encode(
      args as InitializeInstructionParamsInstructionDataArgs
    ),
  } as InitializeInstructionParamsInstruction<
    TProgramAddress,
    TAccountSigner,
    TAccountInstructionParams,
    TAccountSystemProgram
  >;

  return instruction;
}

export type ParsedInitializeInstructionParamsInstruction<
  TProgram extends string = typeof SVM_SPOKE_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    signer: TAccountMetas[0];
    instructionParams: TAccountMetas[1];
    systemProgram: TAccountMetas[2];
  };
  data: InitializeInstructionParamsInstructionData;
};

export function parseInitializeInstructionParamsInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>
): ParsedInitializeInstructionParamsInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 3) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = instruction.accounts![accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      signer: getNextAccount(),
      instructionParams: getNextAccount(),
      systemProgram: getNextAccount(),
    },
    data: getInitializeInstructionParamsInstructionDataDecoder().decode(
      instruction.data
    ),
  };
}
