/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  addDecoderSizePrefix,
  addEncoderSizePrefix,
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  getU32Decoder,
  getU32Encoder,
  getU64Decoder,
  getU64Encoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from '@solana/kit';
import { SVM_SPOKE_PROGRAM_ADDRESS } from '../programs';
import {
  expectAddress,
  expectSome,
  getAccountMetaFactory,
  type ResolvedAccount,
} from '../shared';

export const UNSAFE_DEPOSIT_DISCRIMINATOR = new Uint8Array([
  196, 187, 166, 179, 3, 146, 150, 246,
]);

export function getUnsafeDepositDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    UNSAFE_DEPOSIT_DISCRIMINATOR
  );
}

export type UnsafeDepositInstruction<
  TProgram extends string = typeof SVM_SPOKE_PROGRAM_ADDRESS,
  TAccountSigner extends string | AccountMeta<string> = string,
  TAccountState extends string | AccountMeta<string> = string,
  TAccountDelegate extends string | AccountMeta<string> = string,
  TAccountDepositorTokenAccount extends string | AccountMeta<string> = string,
  TAccountVault extends string | AccountMeta<string> = string,
  TAccountMint extends string | AccountMeta<string> = string,
  TAccountTokenProgram extends string | AccountMeta<string> =
    'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA',
  TAccountAssociatedTokenProgram extends string | AccountMeta<string> =
    'ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL',
  TAccountSystemProgram extends string | AccountMeta<string> =
    '11111111111111111111111111111111',
  TAccountEventAuthority extends string | AccountMeta<string> = string,
  TAccountProgram extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountSigner extends string
        ? WritableSignerAccount<TAccountSigner> &
            AccountSignerMeta<TAccountSigner>
        : TAccountSigner,
      TAccountState extends string
        ? WritableAccount<TAccountState>
        : TAccountState,
      TAccountDelegate extends string
        ? ReadonlyAccount<TAccountDelegate>
        : TAccountDelegate,
      TAccountDepositorTokenAccount extends string
        ? WritableAccount<TAccountDepositorTokenAccount>
        : TAccountDepositorTokenAccount,
      TAccountVault extends string
        ? WritableAccount<TAccountVault>
        : TAccountVault,
      TAccountMint extends string
        ? ReadonlyAccount<TAccountMint>
        : TAccountMint,
      TAccountTokenProgram extends string
        ? ReadonlyAccount<TAccountTokenProgram>
        : TAccountTokenProgram,
      TAccountAssociatedTokenProgram extends string
        ? ReadonlyAccount<TAccountAssociatedTokenProgram>
        : TAccountAssociatedTokenProgram,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      TAccountEventAuthority extends string
        ? ReadonlyAccount<TAccountEventAuthority>
        : TAccountEventAuthority,
      TAccountProgram extends string
        ? ReadonlyAccount<TAccountProgram>
        : TAccountProgram,
      ...TRemainingAccounts,
    ]
  >;

export type UnsafeDepositInstructionData = {
  discriminator: ReadonlyUint8Array;
  depositor: Address;
  recipient: Address;
  inputToken: Address;
  outputToken: Address;
  inputAmount: bigint;
  outputAmount: ReadonlyUint8Array;
  destinationChainId: bigint;
  exclusiveRelayer: Address;
  depositNonce: bigint;
  quoteTimestamp: number;
  fillDeadline: number;
  exclusivityParameter: number;
  message: ReadonlyUint8Array;
};

export type UnsafeDepositInstructionDataArgs = {
  depositor: Address;
  recipient: Address;
  inputToken: Address;
  outputToken: Address;
  inputAmount: number | bigint;
  outputAmount: ReadonlyUint8Array;
  destinationChainId: number | bigint;
  exclusiveRelayer: Address;
  depositNonce: number | bigint;
  quoteTimestamp: number;
  fillDeadline: number;
  exclusivityParameter: number;
  message: ReadonlyUint8Array;
};

export function getUnsafeDepositInstructionDataEncoder(): Encoder<UnsafeDepositInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ['discriminator', fixEncoderSize(getBytesEncoder(), 8)],
      ['depositor', getAddressEncoder()],
      ['recipient', getAddressEncoder()],
      ['inputToken', getAddressEncoder()],
      ['outputToken', getAddressEncoder()],
      ['inputAmount', getU64Encoder()],
      ['outputAmount', fixEncoderSize(getBytesEncoder(), 32)],
      ['destinationChainId', getU64Encoder()],
      ['exclusiveRelayer', getAddressEncoder()],
      ['depositNonce', getU64Encoder()],
      ['quoteTimestamp', getU32Encoder()],
      ['fillDeadline', getU32Encoder()],
      ['exclusivityParameter', getU32Encoder()],
      ['message', addEncoderSizePrefix(getBytesEncoder(), getU32Encoder())],
    ]),
    (value) => ({ ...value, discriminator: UNSAFE_DEPOSIT_DISCRIMINATOR })
  );
}

export function getUnsafeDepositInstructionDataDecoder(): Decoder<UnsafeDepositInstructionData> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
    ['depositor', getAddressDecoder()],
    ['recipient', getAddressDecoder()],
    ['inputToken', getAddressDecoder()],
    ['outputToken', getAddressDecoder()],
    ['inputAmount', getU64Decoder()],
    ['outputAmount', fixDecoderSize(getBytesDecoder(), 32)],
    ['destinationChainId', getU64Decoder()],
    ['exclusiveRelayer', getAddressDecoder()],
    ['depositNonce', getU64Decoder()],
    ['quoteTimestamp', getU32Decoder()],
    ['fillDeadline', getU32Decoder()],
    ['exclusivityParameter', getU32Decoder()],
    ['message', addDecoderSizePrefix(getBytesDecoder(), getU32Decoder())],
  ]);
}

export function getUnsafeDepositInstructionDataCodec(): Codec<
  UnsafeDepositInstructionDataArgs,
  UnsafeDepositInstructionData
> {
  return combineCodec(
    getUnsafeDepositInstructionDataEncoder(),
    getUnsafeDepositInstructionDataDecoder()
  );
}

export type UnsafeDepositAsyncInput<
  TAccountSigner extends string = string,
  TAccountState extends string = string,
  TAccountDelegate extends string = string,
  TAccountDepositorTokenAccount extends string = string,
  TAccountVault extends string = string,
  TAccountMint extends string = string,
  TAccountTokenProgram extends string = string,
  TAccountAssociatedTokenProgram extends string = string,
  TAccountSystemProgram extends string = string,
  TAccountEventAuthority extends string = string,
  TAccountProgram extends string = string,
> = {
  signer: TransactionSigner<TAccountSigner>;
  state: Address<TAccountState>;
  delegate: Address<TAccountDelegate>;
  depositorTokenAccount?: Address<TAccountDepositorTokenAccount>;
  vault?: Address<TAccountVault>;
  mint: Address<TAccountMint>;
  tokenProgram?: Address<TAccountTokenProgram>;
  associatedTokenProgram?: Address<TAccountAssociatedTokenProgram>;
  systemProgram?: Address<TAccountSystemProgram>;
  eventAuthority?: Address<TAccountEventAuthority>;
  program: Address<TAccountProgram>;
  depositor: UnsafeDepositInstructionDataArgs['depositor'];
  recipient: UnsafeDepositInstructionDataArgs['recipient'];
  inputToken: UnsafeDepositInstructionDataArgs['inputToken'];
  outputToken: UnsafeDepositInstructionDataArgs['outputToken'];
  inputAmount: UnsafeDepositInstructionDataArgs['inputAmount'];
  outputAmount: UnsafeDepositInstructionDataArgs['outputAmount'];
  destinationChainId: UnsafeDepositInstructionDataArgs['destinationChainId'];
  exclusiveRelayer: UnsafeDepositInstructionDataArgs['exclusiveRelayer'];
  depositNonce: UnsafeDepositInstructionDataArgs['depositNonce'];
  quoteTimestamp: UnsafeDepositInstructionDataArgs['quoteTimestamp'];
  fillDeadline: UnsafeDepositInstructionDataArgs['fillDeadline'];
  exclusivityParameter: UnsafeDepositInstructionDataArgs['exclusivityParameter'];
  message: UnsafeDepositInstructionDataArgs['message'];
};

export async function getUnsafeDepositInstructionAsync<
  TAccountSigner extends string,
  TAccountState extends string,
  TAccountDelegate extends string,
  TAccountDepositorTokenAccount extends string,
  TAccountVault extends string,
  TAccountMint extends string,
  TAccountTokenProgram extends string,
  TAccountAssociatedTokenProgram extends string,
  TAccountSystemProgram extends string,
  TAccountEventAuthority extends string,
  TAccountProgram extends string,
  TProgramAddress extends Address = typeof SVM_SPOKE_PROGRAM_ADDRESS,
>(
  input: UnsafeDepositAsyncInput<
    TAccountSigner,
    TAccountState,
    TAccountDelegate,
    TAccountDepositorTokenAccount,
    TAccountVault,
    TAccountMint,
    TAccountTokenProgram,
    TAccountAssociatedTokenProgram,
    TAccountSystemProgram,
    TAccountEventAuthority,
    TAccountProgram
  >,
  config?: { programAddress?: TProgramAddress }
): Promise<
  UnsafeDepositInstruction<
    TProgramAddress,
    TAccountSigner,
    TAccountState,
    TAccountDelegate,
    TAccountDepositorTokenAccount,
    TAccountVault,
    TAccountMint,
    TAccountTokenProgram,
    TAccountAssociatedTokenProgram,
    TAccountSystemProgram,
    TAccountEventAuthority,
    TAccountProgram
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? SVM_SPOKE_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    signer: { value: input.signer ?? null, isWritable: true },
    state: { value: input.state ?? null, isWritable: true },
    delegate: { value: input.delegate ?? null, isWritable: false },
    depositorTokenAccount: {
      value: input.depositorTokenAccount ?? null,
      isWritable: true,
    },
    vault: { value: input.vault ?? null, isWritable: true },
    mint: { value: input.mint ?? null, isWritable: false },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
    associatedTokenProgram: {
      value: input.associatedTokenProgram ?? null,
      isWritable: false,
    },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
    eventAuthority: { value: input.eventAuthority ?? null, isWritable: false },
    program: { value: input.program ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA' as Address<'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA'>;
  }
  if (!accounts.depositorTokenAccount.value) {
    accounts.depositorTokenAccount.value = await getProgramDerivedAddress({
      programAddress:
        'ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL' as Address<'ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL'>,
      seeds: [
        getAddressEncoder().encode(expectSome(args.depositor)),
        getAddressEncoder().encode(expectAddress(accounts.tokenProgram.value)),
        getAddressEncoder().encode(expectAddress(accounts.mint.value)),
      ],
    });
  }
  if (!accounts.vault.value) {
    accounts.vault.value = await getProgramDerivedAddress({
      programAddress:
        'ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL' as Address<'ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL'>,
      seeds: [
        getAddressEncoder().encode(expectAddress(accounts.state.value)),
        getAddressEncoder().encode(expectAddress(accounts.tokenProgram.value)),
        getAddressEncoder().encode(expectAddress(accounts.mint.value)),
      ],
    });
  }
  if (!accounts.associatedTokenProgram.value) {
    accounts.associatedTokenProgram.value =
      'ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL' as Address<'ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL'>;
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      '11111111111111111111111111111111' as Address<'11111111111111111111111111111111'>;
  }
  if (!accounts.eventAuthority.value) {
    accounts.eventAuthority.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([
            95, 95, 101, 118, 101, 110, 116, 95, 97, 117, 116, 104, 111, 114,
            105, 116, 121,
          ])
        ),
      ],
    });
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.signer),
      getAccountMeta(accounts.state),
      getAccountMeta(accounts.delegate),
      getAccountMeta(accounts.depositorTokenAccount),
      getAccountMeta(accounts.vault),
      getAccountMeta(accounts.mint),
      getAccountMeta(accounts.tokenProgram),
      getAccountMeta(accounts.associatedTokenProgram),
      getAccountMeta(accounts.systemProgram),
      getAccountMeta(accounts.eventAuthority),
      getAccountMeta(accounts.program),
    ],
    programAddress,
    data: getUnsafeDepositInstructionDataEncoder().encode(
      args as UnsafeDepositInstructionDataArgs
    ),
  } as UnsafeDepositInstruction<
    TProgramAddress,
    TAccountSigner,
    TAccountState,
    TAccountDelegate,
    TAccountDepositorTokenAccount,
    TAccountVault,
    TAccountMint,
    TAccountTokenProgram,
    TAccountAssociatedTokenProgram,
    TAccountSystemProgram,
    TAccountEventAuthority,
    TAccountProgram
  >;

  return instruction;
}

export type UnsafeDepositInput<
  TAccountSigner extends string = string,
  TAccountState extends string = string,
  TAccountDelegate extends string = string,
  TAccountDepositorTokenAccount extends string = string,
  TAccountVault extends string = string,
  TAccountMint extends string = string,
  TAccountTokenProgram extends string = string,
  TAccountAssociatedTokenProgram extends string = string,
  TAccountSystemProgram extends string = string,
  TAccountEventAuthority extends string = string,
  TAccountProgram extends string = string,
> = {
  signer: TransactionSigner<TAccountSigner>;
  state: Address<TAccountState>;
  delegate: Address<TAccountDelegate>;
  depositorTokenAccount: Address<TAccountDepositorTokenAccount>;
  vault: Address<TAccountVault>;
  mint: Address<TAccountMint>;
  tokenProgram?: Address<TAccountTokenProgram>;
  associatedTokenProgram?: Address<TAccountAssociatedTokenProgram>;
  systemProgram?: Address<TAccountSystemProgram>;
  eventAuthority: Address<TAccountEventAuthority>;
  program: Address<TAccountProgram>;
  depositor: UnsafeDepositInstructionDataArgs['depositor'];
  recipient: UnsafeDepositInstructionDataArgs['recipient'];
  inputToken: UnsafeDepositInstructionDataArgs['inputToken'];
  outputToken: UnsafeDepositInstructionDataArgs['outputToken'];
  inputAmount: UnsafeDepositInstructionDataArgs['inputAmount'];
  outputAmount: UnsafeDepositInstructionDataArgs['outputAmount'];
  destinationChainId: UnsafeDepositInstructionDataArgs['destinationChainId'];
  exclusiveRelayer: UnsafeDepositInstructionDataArgs['exclusiveRelayer'];
  depositNonce: UnsafeDepositInstructionDataArgs['depositNonce'];
  quoteTimestamp: UnsafeDepositInstructionDataArgs['quoteTimestamp'];
  fillDeadline: UnsafeDepositInstructionDataArgs['fillDeadline'];
  exclusivityParameter: UnsafeDepositInstructionDataArgs['exclusivityParameter'];
  message: UnsafeDepositInstructionDataArgs['message'];
};

export function getUnsafeDepositInstruction<
  TAccountSigner extends string,
  TAccountState extends string,
  TAccountDelegate extends string,
  TAccountDepositorTokenAccount extends string,
  TAccountVault extends string,
  TAccountMint extends string,
  TAccountTokenProgram extends string,
  TAccountAssociatedTokenProgram extends string,
  TAccountSystemProgram extends string,
  TAccountEventAuthority extends string,
  TAccountProgram extends string,
  TProgramAddress extends Address = typeof SVM_SPOKE_PROGRAM_ADDRESS,
>(
  input: UnsafeDepositInput<
    TAccountSigner,
    TAccountState,
    TAccountDelegate,
    TAccountDepositorTokenAccount,
    TAccountVault,
    TAccountMint,
    TAccountTokenProgram,
    TAccountAssociatedTokenProgram,
    TAccountSystemProgram,
    TAccountEventAuthority,
    TAccountProgram
  >,
  config?: { programAddress?: TProgramAddress }
): UnsafeDepositInstruction<
  TProgramAddress,
  TAccountSigner,
  TAccountState,
  TAccountDelegate,
  TAccountDepositorTokenAccount,
  TAccountVault,
  TAccountMint,
  TAccountTokenProgram,
  TAccountAssociatedTokenProgram,
  TAccountSystemProgram,
  TAccountEventAuthority,
  TAccountProgram
> {
  // Program address.
  const programAddress = config?.programAddress ?? SVM_SPOKE_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    signer: { value: input.signer ?? null, isWritable: true },
    state: { value: input.state ?? null, isWritable: true },
    delegate: { value: input.delegate ?? null, isWritable: false },
    depositorTokenAccount: {
      value: input.depositorTokenAccount ?? null,
      isWritable: true,
    },
    vault: { value: input.vault ?? null, isWritable: true },
    mint: { value: input.mint ?? null, isWritable: false },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
    associatedTokenProgram: {
      value: input.associatedTokenProgram ?? null,
      isWritable: false,
    },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
    eventAuthority: { value: input.eventAuthority ?? null, isWritable: false },
    program: { value: input.program ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA' as Address<'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA'>;
  }
  if (!accounts.associatedTokenProgram.value) {
    accounts.associatedTokenProgram.value =
      'ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL' as Address<'ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL'>;
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      '11111111111111111111111111111111' as Address<'11111111111111111111111111111111'>;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.signer),
      getAccountMeta(accounts.state),
      getAccountMeta(accounts.delegate),
      getAccountMeta(accounts.depositorTokenAccount),
      getAccountMeta(accounts.vault),
      getAccountMeta(accounts.mint),
      getAccountMeta(accounts.tokenProgram),
      getAccountMeta(accounts.associatedTokenProgram),
      getAccountMeta(accounts.systemProgram),
      getAccountMeta(accounts.eventAuthority),
      getAccountMeta(accounts.program),
    ],
    programAddress,
    data: getUnsafeDepositInstructionDataEncoder().encode(
      args as UnsafeDepositInstructionDataArgs
    ),
  } as UnsafeDepositInstruction<
    TProgramAddress,
    TAccountSigner,
    TAccountState,
    TAccountDelegate,
    TAccountDepositorTokenAccount,
    TAccountVault,
    TAccountMint,
    TAccountTokenProgram,
    TAccountAssociatedTokenProgram,
    TAccountSystemProgram,
    TAccountEventAuthority,
    TAccountProgram
  >;

  return instruction;
}

export type ParsedUnsafeDepositInstruction<
  TProgram extends string = typeof SVM_SPOKE_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    signer: TAccountMetas[0];
    state: TAccountMetas[1];
    delegate: TAccountMetas[2];
    depositorTokenAccount: TAccountMetas[3];
    vault: TAccountMetas[4];
    mint: TAccountMetas[5];
    tokenProgram: TAccountMetas[6];
    associatedTokenProgram: TAccountMetas[7];
    systemProgram: TAccountMetas[8];
    eventAuthority: TAccountMetas[9];
    program: TAccountMetas[10];
  };
  data: UnsafeDepositInstructionData;
};

export function parseUnsafeDepositInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>
): ParsedUnsafeDepositInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 11) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = instruction.accounts![accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      signer: getNextAccount(),
      state: getNextAccount(),
      delegate: getNextAccount(),
      depositorTokenAccount: getNextAccount(),
      vault: getNextAccount(),
      mint: getNextAccount(),
      tokenProgram: getNextAccount(),
      associatedTokenProgram: getNextAccount(),
      systemProgram: getNextAccount(),
      eventAuthority: getNextAccount(),
      program: getNextAccount(),
    },
    data: getUnsafeDepositInstructionDataDecoder().decode(instruction.data),
  };
}
