/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getStructDecoder,
  getStructEncoder,
  getU32Decoder,
  getU32Encoder,
  type Codec,
  type Decoder,
  type Encoder,
} from '@solana/kit';

export type SignatureThresholdUpdated = {
  oldSignatureThreshold: number;
  newSignatureThreshold: number;
};

export type SignatureThresholdUpdatedArgs = SignatureThresholdUpdated;

export function getSignatureThresholdUpdatedEncoder(): Encoder<SignatureThresholdUpdatedArgs> {
  return getStructEncoder([
    ['oldSignatureThreshold', getU32Encoder()],
    ['newSignatureThreshold', getU32Encoder()],
  ]);
}

export function getSignatureThresholdUpdatedDecoder(): Decoder<SignatureThresholdUpdated> {
  return getStructDecoder([
    ['oldSignatureThreshold', getU32Decoder()],
    ['newSignatureThreshold', getU32Decoder()],
  ]);
}

export function getSignatureThresholdUpdatedCodec(): Codec<
  SignatureThresholdUpdatedArgs,
  SignatureThresholdUpdated
> {
  return combineCodec(
    getSignatureThresholdUpdatedEncoder(),
    getSignatureThresholdUpdatedDecoder()
  );
}
