/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  getU32Decoder,
  getU32Encoder,
  getU64Decoder,
  getU64Encoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type ReadonlyUint8Array,
} from '@solana/kit';
import {
  getRelayExecutionEventInfoDecoder,
  getRelayExecutionEventInfoEncoder,
  type RelayExecutionEventInfo,
  type RelayExecutionEventInfoArgs,
} from '.';

export type FilledRelay = {
  inputToken: Address;
  outputToken: Address;
  inputAmount: ReadonlyUint8Array;
  outputAmount: bigint;
  repaymentChainId: bigint;
  originChainId: bigint;
  depositId: ReadonlyUint8Array;
  fillDeadline: number;
  exclusivityDeadline: number;
  exclusiveRelayer: Address;
  relayer: Address;
  depositor: Address;
  recipient: Address;
  messageHash: ReadonlyUint8Array;
  relayExecutionInfo: RelayExecutionEventInfo;
};

export type FilledRelayArgs = {
  inputToken: Address;
  outputToken: Address;
  inputAmount: ReadonlyUint8Array;
  outputAmount: number | bigint;
  repaymentChainId: number | bigint;
  originChainId: number | bigint;
  depositId: ReadonlyUint8Array;
  fillDeadline: number;
  exclusivityDeadline: number;
  exclusiveRelayer: Address;
  relayer: Address;
  depositor: Address;
  recipient: Address;
  messageHash: ReadonlyUint8Array;
  relayExecutionInfo: RelayExecutionEventInfoArgs;
};

export function getFilledRelayEncoder(): Encoder<FilledRelayArgs> {
  return getStructEncoder([
    ['inputToken', getAddressEncoder()],
    ['outputToken', getAddressEncoder()],
    ['inputAmount', fixEncoderSize(getBytesEncoder(), 32)],
    ['outputAmount', getU64Encoder()],
    ['repaymentChainId', getU64Encoder()],
    ['originChainId', getU64Encoder()],
    ['depositId', fixEncoderSize(getBytesEncoder(), 32)],
    ['fillDeadline', getU32Encoder()],
    ['exclusivityDeadline', getU32Encoder()],
    ['exclusiveRelayer', getAddressEncoder()],
    ['relayer', getAddressEncoder()],
    ['depositor', getAddressEncoder()],
    ['recipient', getAddressEncoder()],
    ['messageHash', fixEncoderSize(getBytesEncoder(), 32)],
    ['relayExecutionInfo', getRelayExecutionEventInfoEncoder()],
  ]);
}

export function getFilledRelayDecoder(): Decoder<FilledRelay> {
  return getStructDecoder([
    ['inputToken', getAddressDecoder()],
    ['outputToken', getAddressDecoder()],
    ['inputAmount', fixDecoderSize(getBytesDecoder(), 32)],
    ['outputAmount', getU64Decoder()],
    ['repaymentChainId', getU64Decoder()],
    ['originChainId', getU64Decoder()],
    ['depositId', fixDecoderSize(getBytesDecoder(), 32)],
    ['fillDeadline', getU32Decoder()],
    ['exclusivityDeadline', getU32Decoder()],
    ['exclusiveRelayer', getAddressDecoder()],
    ['relayer', getAddressDecoder()],
    ['depositor', getAddressDecoder()],
    ['recipient', getAddressDecoder()],
    ['messageHash', fixDecoderSize(getBytesDecoder(), 32)],
    ['relayExecutionInfo', getRelayExecutionEventInfoDecoder()],
  ]);
}

export function getFilledRelayCodec(): Codec<FilledRelayArgs, FilledRelay> {
  return combineCodec(getFilledRelayEncoder(), getFilledRelayDecoder());
}
